__title__ = 'amazoncaptcha'
__description__ = 'Pure Python, lightweight, Pillow-based solver for Amazon\'s text captcha.'
__url__ = 'https://github.com/a-maliarov/amazon-captcha-solver'
__version__ = '0.4.8'
__author__ = 'Anatolii Maliarov'
__author_email__ = 'tly.mov@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2020 Anatolii Maliarov'
